datamade/bga-payroll

- bga_database/jinja2.py
- payroll/views.py
- templates/base.html
- templates/search_results.html
Had a conversation with Starlyn and this is what we came up with to address her concern that it was not super clear that users were creating an account when they signed up. In this PR I:
* Reworded the signup form to make it clearer what was happening
* Added confirmation modals that appear after signup and login that let the user know they are now logged in
* Added an item to the top nav bar that makes it clear site-wide that users are logged in 
* Added a logout button as a dropdown from the above item
> Signup and login refinements

- payroll/views.py
When a user tried to signup when they already had an account and then went to login, they got the message for logging in as well as the message for signing up. This fixes that so they only get the message associated with the appropriate action.
> Only add signup message when signup really occurs

- bga_database/chart_settings.py
- bga_database/static/js/chart_helper.js
- payroll/charts.py
- payroll/views.py
- templates/base.html
this pr adds a composite bin for all salaries exceeding 200k to the distribution chart, so that wide distributions do not produce un-useful charts. closes #306.
(no salaries above 200k)
> Revise distribution charts

- ARCHITECTURE.md
This pull request adds a brief architecture document describing the `payroll` and `data_import` applications, as well as their dependencies.
> Add architecture document

- Dockerfile
- README.md
- requirements.txt
This pull request expands startup documentation somewhat. It also pins the `kombu` dependency, so Celery continues to work. See https://github.com/pydanny/cookiecutter-django/issues/1954.
> Expand startup documentation, pin kombu

- bga_database/local_settings.py.example
- configs/local_settings.py.travis
- docker-compose.yml
- requirements.txt
- tests/data_import/conftest.py
This PR:
- Upgrades Django and Jinja2 to the recommended versions for security reasons, and also to take advantage of new features in Django 2.2, specifically database constraints
- Updates Redis config values so tests pass locally, as well as in CI 
- Confirm the tests pass in CI.
- Rebuild your application container: `docker-compose build app`.
- Run the tests locally: `docker-compose -f docker-compose.yml -f tests/docker-compose.yml pytest -sv`. Confirm they pass.
- Cruise around the local app and confirm that views look and behave as expected.
> Upgrade Django and Jinja, patch Redis tests for local development

- bga_database/static/js/chart_helper.js
- docker-compose.yml
- payroll/views.py
- templates/department.html
- templates/partials/payroll_expenditure.html
- templates/unit.html
This PR adds the chart to the payroll expenditures breakout card on the unit and dept templates. I use Highcharts and Django ORM's Prefetch object to omit null salary `amount` and `extra_pay` fields
Closes #366
> Unit dept chart

- templates/unit.html
This PR makes a small change to resolve a Highcharts error that occurred with Units that have no department children. 
Closes #380
> resolve charting error for units with no depts

- payroll/models.py
- payroll/views.py
- templates/index.html
As I was fixing the queries to select data for the distribution charts on the homepage and employer pages, I noticed there are a handful of queries where we're using salary amount to calculate values. Since it's a boring change and you already figured out the logic, I went ahead and updated them all to use total pay instead.
- Check out this branch and run the application.
- Navigate to a few pages and be sure no exceptions are raised.
> Adjust a handful of queries to consider total pay

- bga_database/static/js/chart_helper.js
- templates/partials/payroll_expenditure.html
- templates/unit.html
This PR adds a bit more coherent and useful styling to the pay breakout chart and top spending departments chart. 
Closes #390 
- Any feedback on the color scheme for the top spending depts chart is appreciated. FYI, from left to right, the 2, 4, and 6th colors are colors taken directly from the page.
- I had a thought to add a tooltip feature for the composition chart that shows the name of the department rather than a percentage amount. Let me know if you think it's useful or redundant.
> Emp chart enhancements

- bga_database/urls.py
- data_import/admin.py
- data_import/forms.py
- data_import/views.py
- templates/data_import/index.html
- tests/data_import/test_upload.py
This PR situates the data-import form in the django admin interface.
Closes #402 
I've been focusing my testing on the `test_upload` tests, they're failing because the urls are still set up to point toward `views.py`. My understanding is they should point toward the `/admin/` url
> Data import admin

- payroll/views.py
- templates/partials/payroll_expenditure.html
- templates/partials/person_table.html
This pull request makes minor changes to copy around how agencies report extra pay in the recently added card for payroll breakout as well as for table changes around separating base and extra pay
Closes #408 and #409 
Upon checking different pages to make sure the copy had been updated appropriately, I noticed that the clicking on a person's link resulted in an error: "Job matching query does not exist."
> Reported pay wording

- bga_database/settings.py
- bga_database/urls.py
- payroll/api.py
- payroll/charts.py
- payroll/models.py
- payroll/serializers.py
- payroll/views.py
- requirements.txt
This PR installs [Django REST framework](https://www.django-rest-framework.org/#quickstart) and migrates calculations for display from view code to API endpoints for the index, units, and departments, and people.
The API expects a data year query parameter, however with the exception of the index endpoint and source file links, it does not yet use data year to filter calculations. This is so we can confirm the endpoints replicate the calculations from the views, before we add additional functionality in a separate PR.
Most of the diff in this PR is reorganizing code!
- All of the employer calculations are migrated verbatim from the view code, i.e., they don't need additional review. The only exception is grabbing salaries for an employer, which was migrated from the Salary model to a …
> Create entity metadata API

- bga_database/static/js/data_year_toggle.js
- payroll/context_processors.py
- payroll/views.py
- templates/jinja2/unit.html
This PR updates the year toggle on the Unit page to show the most recent year with available data. We do this, so search crawlers that execute JavaScript will capture the most information possible about employers (#436). It also adds simple client-side caching to prevent duplicate API calls when toggling between years on a single page.
Closes #436.
> Default to most recent year with data on employer pages

- payroll/management/commands/build_solr_index.py
This PR makes the following changes to the Person indexing operation:
- Use [QuerySet.iterator()](https://docs.djangoproject.com/en/dev/ref/models/querysets/#iterator) to iterate over Person objects
- Only iterate over people with jobs in the given reporting years
> Reduce memory consumption during Person indexing

- payroll/search.py
- payroll/serializers.py
- payroll/views.py
See title. Closes #451, closes #453.
- Navigate to the homepage, and query for "Chicago". Confirm you see distinct unit and person suggestions.
- Navigate to [this person page](https://bga-payroll.datamade.us/person/dennis-reboletti-e4bc2e3e/) and confirm that it is displayed as expected.
> Correctly retrieve the most recent Salary on person pages, deduplicate autosuggestions

- payroll/management/commands/build_solr_index.py
This PR updates person indexing to use salary, which varies each year, rather than job, which appears first in one year but can have related salaries in subsequent years. It closes #455.
- Deploy to the staging site, then run a person reindex.
- Visit the search linked in the issue and confirm there are two results.
> Index person by salary, not job

- payroll/management/commands/build_solr_index.py
- payroll/search.py
- payroll/serializers.py
- templates/jinja2/partials/breadcrumbs.html
See title.
- Total pay: Handles #460, handles #448 
- Solr sanitization: Handles #459, handles #346
- Rebuild the person index
- Visit https://bga-payroll.datamade.us/search/?entity_type=person&employer=calumet-park-71c48e4c&page=16 and confirm the page loads as expected
- Visit http://localhost:8000/search/?name=Walter%20F%20O%22Neil&entity_type=unit%2Cdepartment%2Cperson and confirm the page loads as expected
> Use total pay in person index/serializer, sanitize Solr queries

- bga_database/static/js/employer.js
- payroll/search.py
- payroll/views.py
- templates/jinja2/partials/search_result.html
- templates/jinja2/search_results.html
This PR:
- Adds a data year filter to the search, defaulting to the most recent year if a data year parameter is not provided, closes #458 
- Adds data year parameters to search results, closes #456
- Adds data year parameters to employer links on unit/department detail pages, connects #466
> Add data year filter to search, data year parameters search results and links around the site

- payroll/serializers.py
- templates/jinja2/partials/person_jobs_card.html
This PR only calculates percent change in base/extra pay if the first value is not 0.
Reference: https://money.stackexchange.com/questions/84534/what-is-the-correct-answer-for-percent-change-when-the-start-amount-is-zero-doll
Closes #465.
> Don't calculate percent change when starting amount is 0

- bga_database/static/css/custom.css
- bga_database/static/js/story_feed.js
- bga_database/urls.py
- payroll/views.py
- requirements.txt
- templates/jinja2/department.html
- templates/jinja2/index.html
- templates/jinja2/partials/story_feed.html
- templates/jinja2/person.html
- templates/jinja2/unit.html
This pull request adds a Django endpoint that retrieves stories from BGA's newsroom RSS feed, and JavaScript to hit the endpoint and populate the story feed on the site. I chose to retrieve the feed in Python in order to cache the response and limit the load on BGA servers (rather than hitting their site every time someone visits a page on the Salaries site). I chose to populate the feed in JavaScript because we cache full templates, and we don't want the feed to be coupled with template caching. (Right now, templates and the RSS endpoint are cached for the same amount of time, but we may want to increase timeout for templates prior to launch; implementing feed caching separately grants us this flexibility.)
- Deploy these changes to the staging site. Visit the homepage, a unit page, a …
> Dynamically populate story feed

- templates/jinja2/base.html
- templates/jinja2/person.html
See title.
I tested this locally by adding a test link to the homepage and using the Google Analytics Debugger Chrome extension. This was the output, which matched my expectations:
```
Processing commands (1)
js?id=UA-18960172-1:115 Processing GTAG command: ["event", "downloaded", {event_category: "downloads", event_label: "https://bga-payroll-database.s3.amazonaws.com/2017/payroll/source/None/FOIA_04_2018_EE_Wages_Info.xlsx"}]
analytics.js:25 Executing Google Analytics commands.
analytics.js:25 Running command: ga("create", "UA-18960172-1", {cookieDomain: "auto", name: "gtag_UA_18960172_1"})
analytics.js:25 Ignoring create request for duplicate tracking name.
log @ analytics.js:25
J @ analytics.js:24
Z.create @ analytics.js:109
Y.b.<computed> @ analytics.js:68
jf.R @ analytics.js:108 …
```
> Track source file clicks as Google Analytics events

- README.md
- bga_database/local_settings.py.example
This PR adds instructions for restoring a development database from a dump.
- View the rendered markdown and confirm it looks good.
- Use the dump file provided via Slack to follow the instructions. Confirm you can successfully restore the database and populate your search index.
> Add docs for restoring from dump

- payroll/models.py
This PR squashes the bug meanderingly described in #535.
- Confirm CI passes.
- Merge to deploy to staging.
- [View Leonard M Shoshi](https://bga-payroll.datamade.us/person/leonard-m-shoshi-20e87a51/) and confirm the page loads without error, and the most recent salary is described in the lead text box.
> Order jobs by salary reporting year, not job reporting year

- bga_database/urls.py
- payroll/views.py
- templates/jinja2/partials/employee_card.html
Code changes include:
- New view with a url for downloading a csv. The csv is downloadable by year.
- A link in the template so a user can download the data.
Closes #515.
Any ideas where this link should exist on the webpage? It's not styled, currently.
- Pull down branch `download-csv` and run the app.
- Download data from a department or a unit.
- Let me know if I'm missing any places where this should exist?
> add csv export for processed salary data

- payroll/management/commands/build_solr_index.py
Similarly to #536, this PR addresses a bug that omitted people from indexing if they held their job in a prior year, by selecting people to index based on the vintage of their salary, rather than their job.
- Tested locally by having 2019 data in my database, then running `docker-compose run --rm app python manage.py build_solr_index --entity-types people --reporting_year 2019 --recreate` and finally confirming that the correct number of people were indexed for a sample of employers.
- Once this is approved, I'll reindex the staging site with the same command (omitting reporting year), and we should spot check the examples in #539 to confirm they appear in the search index.
> Correctly filter for salaries in a given year, handles #539

- payroll/views.py
- templates/jinja2/index.html
For issue #555.
I removed some view code that was used for the original search suggestion. It didn't seem necessary for this search?
- pull down `search-suggestion` branch
- build the search index for people...takes a while... `docker-compose exec app python manage.py build_solr_index --reporting_year 2018 --entity-types people --chunksize=25`
- make sure it works as expected
> change search suggestion

- payroll/views.py
Fixes bug from #564.
* pull down `fix_units_in_data_download` branch
* visit a unit and a department
* download a CSV
* make sure that employees are listed as belonging to the right department
> fix departments and downloads in data download, closes #564

- bga_database/static/css/custom.css
- payroll/views.py
- templates/jinja2/partials/employee_card.html
- templates/jinja2/partials/source_link.html
- templates/jinja2/person.html
Closes issues:
- #565
- #566
This includes the new styling + the language change for the source data:
- pull down `download-links` branch
- test links and make sure they look good
> Improve download link styling and source data language

- bga_database/static/js/employer.js
- payroll/views.py
- templates/jinja2/partials/employee_card.html
Closes #569.
Instead of prompting the login modal, I'm hiding the download data button. This is a simpler implementation than trying to get the salsa auth plugin to fit this use case. I discussed with Hannah this implementation. 
I've also added some logic in `employer.js` to check if that button exists before executing the related code, otherwise the data selector gets stuck in a loading state.
- `git pull origin authenticated-download`
- Not sure how to test with the salsa cookie, so you'll need to spoof it in the code. In line 109 of `views.py`, set `context['authenticated']` to `True` and `False` to test.
- Make sure the download data button does or doesn't show, depending on how you spoofed it in the view code.
- Make sure the date selection dropdown loads correctly
- Make sure the …
> show download button for authenticated users only

- bga_database/static/bootstrap/scss/utilities/_position.scss
- bga_database/static/css/bootstrap-overrides.css
- bga_database/static/css/custom.css
- templates/jinja2/department.html
- templates/jinja2/unit.html
Closes issue #531.
The existing `sticky-top` CSS was declared in two places: `bootstrap-overrides.css` and `_position.css`. I changed it in `bootstrap-overrides.css` and this worked. I wasn't sure about the purpose of `_position.css` file since the existing `sticky-top` CSS declaration was already set elsewhere, so I added it there just to be safe.
- Pull down `sticky-button` branch
- Visit a department and unity page
- Make sure the button looks right
> fix sticky button bug

- templates/jinja2/base.html
For issues:
- #556
- #551
This new setup requires some orchestration between the new-ish Google Tag Manager console and the familiar Google Analytics console. It took more time than expected to figure it out, but I understand it now (somewhat). GTM provides non-technical users a way to setup Google Analytics event tracking within the GTM admin console, without making any code changes.
I followed [this guide to implement the click tracking](https://www.analyticsmania.com/post/track-clicks-with-google-analytics-4-and-gtm/).
In the Google Tag Management console, I created two triggers:
1. `Download Source Data Event`
2. `Download Standardized Data Event`
Both of these triggers are attached to the same `Download Data Event Tag`.
When a user clicks on either of the links for the triggers, it …
> add google tag manager with download data event tracking

- .github/workflows/main.yml
- Dockerfile
- bga_database/local_settings.py.example
- requirements.txt
- templates/jinja2/index.html
Includes lead text description updates from bga, and handles an incompatibility issue between pip and python 3.5
> Update intro text, upgrade python to avoid pip errors in workflow
