- payroll/search.py
- payroll/views.py
- templates/search_results.html
This PR begins to implement a search solution that returns results in pages, rather than as one giant blob.
> Improve search efficiency

- README.md
Improving README.md, including:
- instructions for local solr setup
- instructions for using docker-compose with the app
re: datamade#334
> Add local solr setup to docs

- payroll/views.py
- templates/partials/baseball_stats.html
- templates/partials/payroll_expenditure.html
This PR calculates median base, extra, and total pay and renders these stats on the relevant cards on the unit and department pages.
Closes #367 
Closes #374
> Render median base, extra, and total pay

- payroll/models.py
- payroll/views.py
- templates/partials/department_card.html
This PR updates the query in the `UnitView` that gets the data required for the Unit page's department table, and updates the template to display this additional information.
Closes #379
> Update dept table

- bga_database/static/js/chart_helper.js
This PR changes the ordering of the composition chart so that the chart order matches the legend.
Closes #388
> Composition chart

- templates/partials/person_jobs_card.html
- templates/person.html
This PR adds a stub for the person page which will include multiple years' worth of salary and employment information.
Closes #365
> Person page

- data_import/models.py
- data_import/utils/import_utility.py
- data_import/utils/queues.py
- data_import/utils/table_names.py
- tests/data_import/conftest.py
- tests/data_import/test_tasks.py
This PR removes the step where incoming payroll data is reshaped, as it is no longer necessary.
> No longer reshape incoming data

- data_import/utils/import_utility.py
I borked the child employer import queries in #411. This PR blends those changes with the original implementation to repair both the select and insert.
Connects #420.
Here's [the diff](https://github.com/datamade/bga-payroll/compare/a0acf15d9f30e90db2422ee3c83c714af50254ee..b22bc7b6e48045cde4ebf8b2c8058b895e040b97#diff-5515aa86b46d2da9cbf6311bb937c0b2R299) between the original implementation and this PR. (Look for `import_utility.py`, then expand the diff and consult the child employer queries.) It's a little easier to see what's changed.
> Repair child employer select and insert queries

- .travis.yml
- payroll/serializers.py
- tests/payroll/test_status_codes.py
> Filter API response by given year

- bga_database/static/js/chart_helper.js
- bga_database/static/js/employer.js
- payroll/serializers.py
- payroll/views.py
- templates/jinja2/department.html
- templates/jinja2/index.html
- templates/jinja2/unit.html
> Add year toggle to Department page

- bga_database/static/js/chart_helper.js
- payroll/serializers.py
- payroll/utils.py
- payroll/views.py
- templates/jinja2/partials/breadcrumbs.html
- templates/jinja2/partials/person_jobs_card.html
- templates/jinja2/partials/person_table.html
- templates/jinja2/person.html
This PR:
- Updates the Person page to use an API serializer
- Adds a listing of positions over time
- Adds a salaries over time stacked column chart
- Adds net change statistics
- Caps the number of fellow job holders at 25
Closes #428
> Add over time elements to the Person page

- bga_database/static/js/employer.js
- templates/jinja2/partials/department_card.html
- templates/jinja2/partials/employee_card.html
- templates/jinja2/search_results.html
- templates/jinja2/unit.html
This PR closes #471, closes #470.
> Add year param to search links, always show data year select in search results

- data_import/utils/import_utility.py
- tests/data_import/fixtures/standardized_data_sample.2017.csv
- tests/data_import/fixtures/standardized_data_sample.2018.csv
> Update school district classification

- bga_database/static/js/employer.js
- package-lock.json
- package.json
- templates/jinja2/partials/payroll_expenditure.html
> Add polyfill for URLSearchParams, patch reference error

- bga_database/static/css/custom.css
- bga_database/static/js/search.js
- templates/jinja2/base.html
- templates/jinja2/department.html
- templates/jinja2/index.html
- templates/jinja2/partials/baseball_stats.html
- templates/jinja2/partials/donate.html
- templates/jinja2/partials/story_feed.html
- templates/jinja2/person.html
- templates/jinja2/search_results.html
- templates/jinja2/unit.html
- templates/jinja2/user_guide.html
This PR adds the elements listed in the title. It also removes duplicate inspiration logic and the prompt to enter at least three characters, closes #320.
- Run the application locally.
- Cruise around and confirm that the index, search, employer, and person pages generally resemble the wireframes here: https://app.moqups.com/nRK8x8TGjM/view/page/a49b2428c
> Add first draft of Wikipedia banner, donate callouts and story feed

- templates/jinja2/base.html
- templates/jinja2/partials/story_feed.html
This PR updates the Data & Tools link to bettergov.org and adds a standalone nav item for Data & Tools.
- Deploy to staging and confirm the navigation appears as expected. 
Handles #484.
> Update top navigation

- templates/jinja2/index.html
> Add back donate button

- payroll/serializers.py
- payroll/views.py
- templates/jinja2/base.html
- templates/jinja2/department.html
- templates/jinja2/index.html
- templates/jinja2/partials/payroll_expenditure.html
- templates/jinja2/person.html
- templates/jinja2/unit.html
- templates/jinja2/user_guide.html
> Make text updates throughout the site

- payroll/serializers.py
> Refactor Unit salary percentile

- README.md
- docker-compose.yml
Adds some setup steps to the README. Found when doing #512.
See copy changes and add any suggestions/clarifications.
> add additional steps for local development

- bga_database/static/css/custom.css
- templates/jinja2/user_guide.html
Changes copy in the user guide. Closes #557.
- Visit the FAQ section.
- Make sure the text changes look right. Here's the doc for reference: https://docs.google.com/document/d/1bOWtMhfMW-jjzkrM6_vbhnvUeq7DU0jTyYs8DQpSPjU/edit#.
- Click on links and make sure they point to the correct place.
> update user guide

- bga_database/static/js/employer.js
- templates/jinja2/partials/employee_card.html
Fixes bug from #563.
- pull down `download-bugs` branch
- visit a unit and a department
- make sure the download link updates for each entity
- download the data and make sure it's for the correct year
> fix download link bug

- payroll/views.py
@deraj1013 requested this change to headers for the data download since not all extra money is overtime.
Download export and confirm that the "overtime" column in now "other"
> tweak data download header per Jared's request

- bga_database/static/js/employer.js
- payroll/views.py
- templates/jinja2/partials/employee_card.html
For issue #579.
- make sure the download button works locally: `git pull origin authenticated-download`
> revert conditional rendering of download button

- payroll/views.py
- templates/jinja2/base.html
In header, footer, and for the rss
> update incorrect links

- .github/workflows/main.yml
- templates/jinja2/department.html
- templates/jinja2/index.html
- templates/jinja2/partials/inspiration_card.html
- templates/jinja2/person.html
- templates/jinja2/search_results.html
- templates/jinja2/unit.html
Removed lorem ipsum text from the inspiration card. Also moved some repeating elements into the card partial.
Closes #595
* Navigate to pages with the inspiration card (eg. index, person detail, search etc)
* Confirm that the placeholder text is gone
> Remove placeholder text

- bga_database/local_settings.py.example
- configs/test_settings_deployment.py
Quick change to document and expect the new variables for interests/groups and tags
> Add interest and tag vars
